boke/boke/urls.py
from django.contrib import admin
from django.urls import path,include
from index.views import mouse,piano
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('article/',include('article.urls',namespace='article')),
    path('mouse/',mouse,name='mouse'),
    path('piano/',piano,name='piano')
]

boke/index/urls.py
from django.urls import path
from .views import index,city,login,exit,list

app_name='index'
urlpatterns=[
    path('',index.as_view(),name='index'),
    path('city/',city),
    path('login/',login,name='login'),
    path('exit/',exit,name='exit'),
    path('list/<int:type>/<int:page_num>/',list,name='list'),
]

boke/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dcalendar.picker.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    <title>{% block title %}登峰造极境{% endblock %}</title>

    <style>
        #head{
            margin-bottom: 20px;
            height: 80px;
            width:100%;
            box-shadow: 5px 5px 5px gray;
            position: fixed;
            z-index: 999;
        }
        #a1{
            height: 80px !important;
            line-height:unset;
            font-size: 34px;
            margin-right:30px;
        }
        #ul{
            position: relative;
            top:13px;
        }
        .div{
            float: left;
            height: 80px;
            width: 150px;
            font-size:25px;
            line-height: 80px;

            text-align: center;
        }
        .div:hover{
            background-color: lightgray;
            cursor: pointer;
        }
        .wenzhang{
            height: 40px !important;
            font-size:20px;
        }
        .wenzhang>a{
            color:dodgerblue !important;
        }
        a{
            text-decoration: none !important;
        }
        @media (max-width: 800px){
            .div{
                display: none;
            }
        }
        @media (max-width: 1000px){
            #ul{
                display: none;
            }
        }
        @media (max-width: 1300px){
            #hello{
                display: none;
            }
        }

    </style>

</head>



<body>
    <nav id="head" class="navbar navbar-default" role="navigation">
    <div  class="container">
        <div class="navbar-header ">
            <a id="a1" class="navbar-brand" href="{% url 'index:index' %}">登封造极境</a>

            <div class="div" onmouseleave="leave()" onmouseover="over()" onclick="list()">
            <li id="over" class="dropdown">
                <a  class="dropdown-toggle"  data-toggle="dropdown">文章分类<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    {% for category in categorys %}
                    <li class="wenzhang bounceInLeft animated"><a href="/list/{{ category.id }}/1/">{{ category.category_name }}</a></li>
                    {% endfor %}
                </ul>
            </li></div>

            <div class="div"><a href="{% url 'mouse'%}">打地鼠</a></div>
            <div class="div"><a href="{% url 'piano' %}">钢琴</a></div>

        </div>

        <ul id="ul" class="nav navbar-nav navbar-right">
            {% if request.session.username %}
                <li><a id="hello" class=" btn-lg" data-toggle="modal"><span >Hello!</span> {{ request.session.username }}</a></li>
                <li><a class="btn btn-default btn-lg" href="{% url 'index:exit' %}" data-toggle="modal"><span ></span> 退出</a></li>
                <li><a class="btn btn-default btn-default" data-toggle="modal" href="/login/"><span class="glyphicon glyphicon-user"></span> 个人中心</a></li>
            {% else %}
            <li><a class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-registration-mark"></span> 注册</a></li>
            <li><a class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal2"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
            <li><a class="btn btn-default btn-default" data-toggle="modal" href="/"><span class="glyphicon glyphicon-user"></span> 个人中心</a></li>
            {% endif %}

        </ul>
    </div>
</nav>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">注册</h4>
            </div>
            <form id="register" action="/" method="POST">
            {% csrf_token %}
            <div class="modal-body">

                    <span>用户名:</span><br>
                    <input type="text" id="username" name="username"><span id="usererror" style="color:red;"></span><br><br>
                    <span>密码:</span><br>
                    <input type="password" id="password" name="password"><span id="passworderror" style="color:red;"></span><br><br>
                     <span>确认密码:</span><br>
                    <input type="password" id="again" name="again"><span id="againerror" style="color:red;"></span><br>
                    <span style="color: red">{{ error }}</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="submit" id="register" onclick="return fun()" class="btn btn-primary">提交</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">登录</h4>
            </div>
            <form action="/login/" method="POST">
                {% csrf_token %}
            <div class="modal-body">
                <span>用户名:</span><br>
                    <input type="text" id="username2" name="username"><span id="usererror2" style="color:red;"></span><br><br>
                    <span>密码:</span><br>
                    <input type="password" id="password2" name="password"><span id="passworderror2" style="color:red;"></span><br><br>
                    <span style="color: red">{{ error2 }}</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="submit" class="btn btn-primary" onclick="return fun2()">登录</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
    <script type="text/javascript" src="/static/js/login.js"></script>
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    {% block body %}
    {% endblock %}


    <script>
        if($('#hello').text().length>16){
            var hello=$('#hello').text().substr(0,16)
            $('#hello').text(hello+'...')
        }

        function list() {
            window.location.href='/list/0/1/'
        }
        function fun(){
                if($('#username').val().length>12||$('#username').val()=='' || $('#password').val()=='' || $('#again').val()==''){
                    if($('#username').val().length> 12){
                        $('#usererror').text('用户名长度不能大于12')
                    }
                    if($('#username').val()==''){
                        $('#usererror').text('用户名不能为空')
                    }
                    if($('#password').val()==''){
                        $('#passworderror').text('密码不能为空')
                    }
                    if($('#again').val()!=$('#password').val()){
                        $('#againerror').text('密码必须一致')
                    }
                    return false
                }else{
                    return true
                }
                }
        function fun2(){
                if($('#username2').val()=='' || $('#password2').val()==''){
                    return false
                }else{
                    return true
                }
                }
        function over(){
            $('#over').attr('class','dropdown open')
        }
        function leave(){
            $('#over').attr('class','dropdown')
        }
        $(function () {
            $('#username').blur(function () {
                if($(this).val().length==0){
                    $('#usererror').html('账号不能为空').show()
                }
                else if($(this).val().length>12){
                    $('#usererror').html('账号长度不能大于12').show()
                }
                else{
                    $('#usererror').hide()
                }
            })
            $('#password').blur(function () {
                if($(this).val().length==0){
                    $('#passworderror').html('密码不能为空').show()
                }else{
                    $('#passworderror').hide()
                }
            })

            $('#username2').blur(function () {
                if($(this).val().length==0){
                    $('#usererror2').html('账号不能为空').show()
                }else{
                    $('#usererror2').hide()
                }
            })
            $('#password2').blur(function () {
                if($(this).val().length==0){
                    $('#passworderror2').html('密码不能为空').show()
                }else{
                    $('#passworderror2').hide()
                }
            })

        })
    </script>

</body>
</html>

boke/templates/head.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<title>纯CSS3绘制的小猫笑脸动画DEMO演示</title>

<link type="text/css" href="/static/css/maolaoshifu.css" rel="stylesheet"/>

</head>
<body>
<div class="mao_box" style="width:100%; height: 100%;">
	<div class="mao">
		<div class="mao_head">
			<div class="huawen">
				<div><!--头部花纹——左边橙色--></div>
			</div>
		</div>
		<div class="erduo">
			<div></div>
			<div></div>
		</div>
		<div class="yanjing">
			<div>
				<div class="yanquan">
					<div></div>
				</div>
				<div class="yanquan_hedding">

				</div>
				<div class="hong"></div>
			</div>
			<div class="yan_right">
				<div class="yanquan">
					<div></div>
				</div>
				<div class="yanquan_hedding">

				</div>
				<div class="hong"></div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="face_huawen">
			<div class="face_huawen_huawen huawen_left">
				<div></div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>

			</div>
			<div class="face_huawen_huawen huawen_right">
				<div></div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>

			</div>
			<div style="clear:both"></div>
		</div>
		<div class="bizi">
			<div></div>
			<div></div>
			<div></div>
			<div></div>
		</div>
		<div class="zuiba_box">
			<div class="zuiba">
				<div></div>
				<div></div>
				<div></div>
			</div>
		</div>
	</div>
</div>
 
<br><br><br><br><br>

<div style="text-align:center;clear:both">
<script src="/gg_bd_ad_720x90.js" type="text/javascript"></script>
<script src="/follow.js" type="text/javascript"></script>
</div>
</body>
</html>

boke/templates/index.html
<head>
{#    <link rel="stylesheet" href="/static/css/hua.css">#}

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Slicebox - 3D Image Slider with Fallback" />
    <meta name="keywords" content="jquery, css3, 3d, webkit, fallback, slider, css3, 3d transforms, slices, rotate, box, automatic" />
    <meta name="author" content="Pedro Botelho for Codrops" />
    <link rel="shortcut icon" href="../favicon.ico">
    <link rel="stylesheet" type="text/css" href="/static/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/slicebox.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/custom.css" />
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>

    <style>
		h1 {
			margin-top: 100px;
			font-family: 'Microsoft Yahei';
			font-size: 36px;
			color: #019157;
		}
        .top-banner,.clearfix{
            display: none !important;
        }
        #myCarousel{
            width:700px;
            left:0;
        }
        #sb-slider{
            margin: 0;
            max-width: 100% !important;
        }
        body{
            width:100%;
            background-color: rgba(211, 211, 211, 0.15) !important;
            height: 100% !important;
        }

        #all{
            position: relative;
            display: flex;
            flex-wrap: wrap;
            top:100px;
            margin-bottom: 150px;
        }
        #right{
            width: 300px;
            height: 326px;
            font-size: 20px;
            font-style: italic;
            background:linear-gradient(white,darkgray) ;
        }


        #leftbody{
            width:70%;
            border-collapse: collapse;
            margin-top: 30px;
        }
        .recommend{
            width:100%;
            height: 200px;
            display: flex;
            border-top: 1px solid black;
            margin-top:20px;
        }
        .recommend:hover{
            box-shadow: 5px 5px 5px gray;
        }
        #newArticle{
             width:100%;
            border-top: 1px solid black;
            margin-top:20px;
        }
        .newArticle{
            font-size: 20px;
            color:black !important;
        }

        #rightbody{
            width:25%;
            height: 500px;
            padding-top: 50px;
            padding-left: 30px;
            margin-top:30px;
            position: relative;
            left:50px;
        }
        #footer{
            position: absolute;
            bottom: 10px !important;
        }
        @media (max-width: 450px){
            #leftbody{
                width:90% !important;
            }
        }
        @media (max-width: 800px){
            .img{
                width:100% !important;
            }
        }
        @media (max-width: 800px){
            .right,#rightbody{
                display: none;
            }
        }
        @media (max-width: 1200px){
            #right{
                display: none;
            }
        }

    </style>
    <script type="text/javascript" src="/static/js/modernizr.custom.46884.js"></script>
</head>
{% extends 'base.html' %}


{% block body %}
    <div id="father">
         <div id="all" class="container">
         <div class="wrapper" id="myCarousel">
				<ul id="sb-slider" class="sb-slider">
                    {% for article in newarticle %}
					<li>
						<a  href="/article/detail/{{ article.id }}/1/"><img src="/{{ article.tupian }}" alt="image1" style="width: 100%;height: 320px;"/></a>
					</li>
                    {% endfor %}

				</ul>

				<div id="shadow" class="shadow"></div>

				<div id="nav-arrows" class="nav-arrows">
					<a href="#">Next</a>
					<a href="#">Previous</a>
				</div>

			</div>

    <div id="right">
{#        <iframe src="/index/city/" frameborder="1" width="100%" height="100%"></iframe>#}
    </div>


    <div id="leftbody">
        <h2 style="text-align: left">最新文章</h2>
        <div id="newArticle">
            {% for article in newarticle %}
                <div class="newArticle">
                 <span>{{ article.category }}</span>:&#x3000;<a style="color:black;font-size:16px;" href="/article/detail/{{ article.id }}/1/">{{ article.title }}</a>
                </div>
            {% endfor %}
        </div>
        <h2 style="text-align: left">推荐文章</h2>
        {% for article in articles %}
            <div class="recommend">
                <img class="img" src="/{{ article.tupian }}" alt="" style="width: 30%; height: 90%;margin-right: 30px;position:relative;top:5%;">
                <div class="right" style="width: 65%;position:relative;">
                    <div><a href="/article/detail/{{ article.id }}/1/"><h3>{{ article.title }}</h3></a></div>
                    <div><span class="content">{{ article.jianjie }}</span>...<a href="/article/detail/{{ article.id }}/1/">详情</a></div>
                    <section id="footer">
                    <span class="glyphicon glyphicon-user">{{ article.author }}</span>&#x3000;
                    <span class="glyphicon glyphicon-time">{{ article.create_time }}</span>&#x3000;
                    <span class="glyphicon glyphicon-thumbs-up">{{ article.popular }}</span>
                </section>
                </div>

            </div>
        {% endfor %}
    </div>
    <div id="rightbody">
        <h4>qq交流群：869914973</h4>
        <span>微信公众号（佛系公众号）：</span>
        <img src="/static/images/wx.jpg" style="width:200px;height: 200px;" alt="">
    </div>
    </div>


{#     <section>#}
{#        <main>#}
{#            <div></div>#}
{#            <div></div>#}
{#            <div></div>#}
{#        </main>#}
{#    </section>#}
    </div>

    <script>
        (function($) {
        $.fn.snow = function(options) {
        var $flake = $('<div id="flake" />').css({
        'position': 'absolute',
        'top': '-50px'
        }).html('&#10052;'),
        documentHeight = $(document).height(),
        documentWidth = $(document).width(),
        defaults = {
        minSize: 10,
        maxSize: 20,
        newOn: 500,
        flakeColor: "#FFFFFF"
        },
        options = $.extend({},
        defaults, options);
        var interval = setInterval(function() {
        var startPositionLeft = Math.random() * documentWidth - 100,
        startOpacity = 0.5 + Math.random(),
        sizeFlake = options.minSize + Math.random() * options.maxSize,
        endPositionTop = documentHeight - 40,
        endPositionLeft = startPositionLeft - 100 + Math.random() * 200,
        durationFall = documentHeight * 10 + Math.random() * 5000;
        $flake.clone().appendTo('body').css({
        left: startPositionLeft,
        opacity: startOpacity,
        'font-size': sizeFlake,
        color: options.flakeColor
        }).animate({
        top: endPositionTop,
        left: endPositionLeft,
        opacity: 0.2
        },
        durationFall, 'linear',
        function() {
        $(this).remove()
        });
        },
        options.newOn);
        };
        })(jQuery);
        $.fn.snow({
        minSize: 5,
        maxSize: 50,
        newOn: 1000,
        flakeColor: '#FFF'
        });
    </script>
    <script>
        $(function () {
            var seconds=5
            timeInterval=setInterval(function () {
                if(seconds>0){
                    if(seconds==5){
                       $('#right').append('<h3>冥思苦想半天这个地方不知道放啥</h3>')
                        {#$('#span1').text('冥思苦想半天这个地方不知道放啥')#}
                    }
                    if(seconds==4){
                        $('#right').append('<h3>那就随便说说话吧</h3>')
                        {#$('#span2').text('那就随便说说话吧')#}
                    }
                    if(seconds==3){
                        $('#right').append('<h3>但关键说也不知道说啥</h3>')
                        {#$('#span3').text('但关键说也不知道说啥。。')#}
                    }
                    if(seconds==2){
                        $('#right').append('<h3>那么就</h3>')
                        {#$('#span4').text('那么就')#}
                    }
                    if(seconds==1){
                         $('#right').append('<h3>提前给大家拜个早年了</h3>')
                        {#$('#span5').text('提前给大家拜个早年了')#}
                    }
                    seconds--

                }
                else{
                    {#$('#right').text('已失效')#}
                }
            },1000)
        })
    </script>

    <script type="text/javascript" src="http://cdn.staticfile.org/jquery/1.8.2/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.slicebox.js"></script>
    <script type="text/javascript">
        $(function() {

            var Page = (function() {

                var $navArrows = $( '#nav-arrows' ).hide(),
                    $shadow = $( '#shadow' ).hide(),
                    slicebox = $( '#sb-slider' ).slicebox( {
                        onReady : function() {

                            $navArrows.show();
                            $shadow.show();

                        },
                        orientation : 'r',
                        cuboidsRandom : true,
                        disperseFactor : 30
                    } ),

                    init = function() {

                        initEvents();

                    },
                    initEvents = function() {

                        // add navigation events
                        $navArrows.children( ':first' ).on( 'click', function() {

                            slicebox.next();
                            return false;

                        } );

                        $navArrows.children( ':last' ).on( 'click', function() {

                            slicebox.previous();
                            return false;

                        } );

                    };

                    return { init : init };

            })();

            Page.init();

        });
    </script>
    <script src="http://dreamsky.github.io/main/blog/common/init.js"></script>
{% endblock %}

boke/templates/index4.html
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <title>Slicebox - 3D图片滑块效果</title>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Slicebox - 3D Image Slider with Fallback" />
        <meta name="keywords" content="jquery, css3, 3d, webkit, fallback, slider, css3, 3d transforms, slices, rotate, box, automatic" />
		<meta name="author" content="Pedro Botelho for Codrops" />
		<link rel="shortcut icon" href="../favicon.ico"> 
        <link rel="stylesheet" type="text/css" href="/static/css/demo.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/slicebox.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/custom.css" />
		<link rel="stylesheet" href="http://dreamsky.github.io/main/blog/common/init.css">
		<style>
		.top-banner {
			background-color: rgba(255, 255, 255, 0.55);
		}
		.top-banner a {
			color: #019135;
		}
		h1 {
			margin-top: 100px;
			font-family: 'Microsoft Yahei';
			font-size: 36px;
			color: #019157;
		}
		</style>			
		<script type="text/javascript" src="/static/js/modernizr.custom.46884.js"></script>
	</head>
	<body>
		<div class="container">


			<div class="wrapper">

				<ul id="sb-slider" class="sb-slider">
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/1.jpg" alt="image1"/></a>
						<div class="sb-description">
							<h3>Creative Lifesaver</h3>
						</div>
					</li>
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/2.jpg" alt="image2"/></a>
						<div class="sb-description">
							<h3>Honest Entertainer</h3>
						</div>
					</li>
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/3.jpg" alt="image1"/></a>
						<div class="sb-description">
							<h3>Brave Astronaut</h3>
						</div>
					</li>
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/4.jpg" alt="image1"/></a>
						<div class="sb-description">
							<h3>Affectionate Decision Maker</h3>
						</div>
					</li>
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/5.jpg" alt="image1"/></a>
						<div class="sb-description">
							<h3>Faithful Investor</h3>
						</div>
					</li>
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/6.jpg" alt="image1"/></a>
						<div class="sb-description">
							<h3>Groundbreaking Artist</h3>
						</div>
					</li>
					<li>
						<a href="http://www.cnblogs.com/lhb25/" target="_blank"><img src="/static/images/7.jpg" alt="image1"/></a>
						<div class="sb-description">
							<h3>Selfless Philantropist</h3>
						</div>
					</li>
				</ul>

				<div id="shadow" class="shadow"></div>

				<div id="nav-arrows" class="nav-arrows">
					<a href="#">Next</a>
					<a href="#">Previous</a>
				</div>

			</div><!-- /wrapper -->
			<div class="footer-banner" style="width:728px; margin:30px auto"></div>
		</div>
		<script type="text/javascript" src="http://cdn.staticfile.org/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery.slicebox.js"></script>
		<script type="text/javascript">
			$(function() {
				
				var Page = (function() {

					var $navArrows = $( '#nav-arrows' ).hide(),
						$shadow = $( '#shadow' ).hide(),
						slicebox = $( '#sb-slider' ).slicebox( {
							onReady : function() {

								$navArrows.show();
								$shadow.show();

							},
							orientation : 'r',
							cuboidsRandom : true,
							disperseFactor : 30
						} ),
						
						init = function() {

							initEvents();
							
						},
						initEvents = function() {

							// add navigation events
							$navArrows.children( ':first' ).on( 'click', function() {

								slicebox.next();
								return false;

							} );

							$navArrows.children( ':last' ).on( 'click', function() {
								
								slicebox.previous();
								return false;

							} );

						};

						return { init : init };

				})();

				Page.init();

			});
		</script>
		<script src="http://dreamsky.github.io/main/blog/common/init.js"></script>
	</body>
</html>	

boke/templates/打地鼠.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>打地鼠</title>
    <style>
        html,body{
            height:100%;
            margin:0;
        }
        body{
            background-image: url(/static/image/bg.jpg);
            /* 指针 */
            cursor: url(/static/image/cursor.png),auto;
        }
        table{
            width:600px;
            height:600px;

            margin:0 auto;
            border-collapse: collapse;
        }
        td{
            width:150px;
            height:150px;

            background-image: url(/static/image/hole.png);
            background-size:120px 50px;
            background-repeat: no-repeat;
            background-position: center bottom;
            text-align: center;
            /* 设置图片从底部出现 */
            vertical-align: bottom;
        }
        img{
            width:80px;
            height:0px;
            position: relative;
            top:-8px;
        }
        .mouseUp{
            animation:up 0.3s ;
            /* 保持动画结束时刻的状态 */
            animation-fill-mode: forwards;
        }
        .mouseDown{
            animation: down 0.1s;
            animation-fill-mode: forwards;
        }
        @keyframes down{
            0%{
                height:70px;
            }
            100%{
                height:0px;
            }
        }
        @keyframes up{
            0%{
                height:0px;
            }
            100%{
                height:70px;
            }
        }
        #defen{
            position: relative;
            top:50px;
            font-size: 30px;
            background-color: rgba(100,100,100,0.7);
            width:120px;
            padding:0px 10px 0 30px;
            border-top-right-radius: 5px;
            border-bottom-right-radius: 5px;
        }
    </style>
</head>
<body>
    <!-- autoplay loop循环播放 -->
    <audio src="/static/audio/music.mp3" autoplay loop></audio>
    <audio id="dazhong"></audio>
    <div id="defen">得分：0</div>
    <table>
        <tr>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
        </tr>
        <tr>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
        </tr>
        <tr>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
        </tr>
        <tr>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
            <td><img src="/static/image/mouse.png" alt=""></td>
        </tr> 
    </table>

     <script src="/static/jquery.js"></script>
    <script>
        // var mouses=document.getElementsByTagName('img')
        // $代表一个jquery对象
        // $=jQuery()
        var mouses=$('img')
        var fenshu=0;

        function showMouse(){
            var random=Math.random()*16
            //Math.floor获取一个不大于该数值的最大整数
            random=Math.floor(random)
            // 获取一个指定的地鼠
            var mouse=mouses.get(random)
            $(mouse).addClass('mouseUp').removeClass('mouseDown')
            
            // setTimeOUt延时 超时
            // 只执行一次
            setTimeout(function(){
                $(mouse).addClass('mouseDown').removeClass('mouseUp')
            },2500)
            // setInterval(function(){
            // 会执行多次
            // },2000)
        }
        function play(){
            setTimeout(showMouse)
            setTimeout(showMouse,100)
            setTimeout(showMouse,500)
            setTimeout(showMouse,1500)
            setTimeout(showMouse,2000)
            setTimeout(showMouse,2500)
        }
        setInterval(play,3000)

        //$('.类名')$('#id名') $('标签') $(变量名)
        $('body').mousedown(function(){
            //更改标签的css样式
            $('body').css('cursor','url(/static/image/cursor-down.png),auto')
        }).mouseup(function(){
            $('body').css('cursor','url(/static/image/cursor.png),auto')
        })
        $(mouses).click(function(){
            // $(this)指的是当前被点击的对象
            $(this).addClass('mouseDown').removeClass('mouseUp')
            fenshu+=10;
            //更改标签文本
            $('#defen').text('得分:'+fenshu)
            
            //更改标签属性
            $('#dazhong').attr('src','/static/audio/dazhong.wav').get(0).play()
        })
        
    </script>
</body>
</html>